router id 3.3.3.3;

protocol device {
    scan time 2;
}

protocol direct {
    ipv4;
    interface "eth*";
}

protocol kernel {
    ipv4 { export all; import all; };
}

protocol bgp R2 {
    local as 65002;
    neighbor 10.2.3.2 as 65002;

    rr client;

    ipv4 {
        import all;
        export all;
	next hop self;
    };
}

protocol bgp R4 {
    local as 65002;
    neighbor 10.3.4.4 as 65002;

    rr client;

    ipv4 {
        import all;
        export all;
	next hop self;
    };
}
