router id 2.2.2.2;

protocol device {
    scan time 2;
}

protocol direct {
    ipv4;
    interface "eth*";
}

protocol kernel {
    ipv4 { export all; import all; };
}

protocol rip UniRIP {
    ipv4 {
        import all;
        export all;
    };

    interface "eth1" {
        mode multicast;
    };

    interface "eth2" {
        mode multicast;
    };

    interface "eth3" {
        mode multicast;
    };
}
