router id 5.5.5.5;

protocol device {
    scan time 2;
}

protocol direct {
    ipv4;
    interface "eth*";
}

protocol kernel {
    ipv4 { export all; import all; };
}

protocol ospf v2 UniOSPF {
    ipv4 { import all; export all; };
    area 0 {
        interface "eth1";
    };
}
