router id 2.2.2.2;

protocol device {
    scan time 2;
}

protocol direct {
    ipv4;
    interface "eth*";
}

protocol kernel {
    ipv4 { export all; import all; };
}

protocol bgp R1 {
    local as 65002;
    neighbor 10.1.2.1 as 65001;

    ipv4 {
        import all;
        export all;
    };
}

protocol bgp R3 {
    local as 65002;
    neighbor 10.2.3.3 as 65002;

    ipv4 {
        import all;
        export all;
    };
}

protocol bgp R4 {
    local as 65002;
    neighbor 10.2.4.4 as 65002;

    ipv4 {
        import all;
        export all;
    };
}
